name = "worker-auth-providers"
type = "webpack"
account_id = "ea5d8d3c03a46b28e8c9f25ae1c09ca8"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"

[site]
bucket = "../dist/client"
entry-point = "."
